"""track knowledge

Revision ID: 92cc84e4b207
Revises: c50f98e2c6fb
Create Date: 2026-10-10 20:17:12.730646
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '92cc84e4b207'
down_revision: Union[str, None] = 'c50f98e2c6fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.SmallInteger(), nullable=False),
    sa.Column('clean_laps', sa.Integer(), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'track_id')
    )
    op.create_index(op.f('ix_track_knowledge_tenant_id'), 'track_knowledge', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_track_knowledge_tenant_id'), table_name='track_knowledge')
    op.drop_table('track_knowledge')
    # ### end Alembic commands ###
