"""track layouts built from telemetry

Revision ID: a7b184d54fc9
Revises: 05fd98fa34e0
Create Date: 2026-09-26 23:13:59.376942
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a7b184d54fc9'
down_revision: Union[str, None] = '05fd98fa34e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track_layouts',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('track_length_m', sa.Float(), nullable=False),
    sa.Column('bin_m', sa.Float(), nullable=False),
    sa.Column('sums', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('points', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('coverage', sa.Float(), nullable=False),
    sa.Column('ready', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('track_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_layouts')
    # ### end Alembic commands ###
