"""mcp oauth and tokens

Revision ID: c50f98e2c6fb
Revises: de9c03b6f9cf
Create Date: 2026-10-05 20:58:51.859484
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c50f98e2c6fb'
down_revision: Union[str, None] = 'de9c03b6f9cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_oauth_authorizations',
    sa.Column('txn_id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('redirect_uri', sa.String(length=700), nullable=False),
    sa.Column('redirect_uri_provided_explicitly', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(length=500), nullable=True),
    sa.Column('scopes', sa.String(length=300), nullable=False),
    sa.Column('code_challenge', sa.String(length=200), nullable=False),
    sa.Column('resource', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('txn_id')
    )
    op.create_index(op.f('ix_mcp_oauth_authorizations_client_id'), 'mcp_oauth_authorizations', ['client_id'], unique=False)
    op.create_table('mcp_oauth_clients',
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('client_secret', sa.String(length=128), nullable=True),
    sa.Column('client_secret_expires_at', sa.BigInteger(), nullable=True),
    sa.Column('client_id_issued_at', sa.BigInteger(), nullable=True),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('client_uri', sa.String(length=500), nullable=True),
    sa.Column('logo_uri', sa.String(length=500), nullable=True),
    sa.Column('redirect_uris', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('grant_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scope', sa.String(length=200), nullable=True),
    sa.Column('token_endpoint_auth_method', sa.String(length=40), nullable=True),
    sa.Column('software_id', sa.String(length=100), nullable=True),
    sa.Column('software_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('mcp_auth_codes',
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('scopes', sa.String(length=300), nullable=False),
    sa.Column('code_challenge', sa.String(length=200), nullable=False),
    sa.Column('redirect_uri', sa.String(length=700), nullable=False),
    sa.Column('redirect_uri_provided_explicitly', sa.Boolean(), nullable=False),
    sa.Column('resource', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code_hash')
    )
    op.create_index(op.f('ix_mcp_auth_codes_client_id'), 'mcp_auth_codes', ['client_id'], unique=False)
    op.create_table('mcp_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_prefix', sa.String(length=24), nullable=False),
    sa.Column('grant_id', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('scopes', sa.String(length=300), nullable=False),
    sa.Column('resource', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['mcp_tokens.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_tokens_grant_id'), 'mcp_tokens', ['grant_id'], unique=False)
    op.create_index(op.f('ix_mcp_tokens_tenant_id'), 'mcp_tokens', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_mcp_tokens_token_hash'), 'mcp_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_mcp_tokens_user_id'), 'mcp_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mcp_tokens_user_id'), table_name='mcp_tokens')
    op.drop_index(op.f('ix_mcp_tokens_token_hash'), table_name='mcp_tokens')
    op.drop_index(op.f('ix_mcp_tokens_tenant_id'), table_name='mcp_tokens')
    op.drop_index(op.f('ix_mcp_tokens_grant_id'), table_name='mcp_tokens')
    op.drop_table('mcp_tokens')
    op.drop_index(op.f('ix_mcp_auth_codes_client_id'), table_name='mcp_auth_codes')
    op.drop_table('mcp_auth_codes')
    op.drop_table('mcp_oauth_clients')
    op.drop_index(op.f('ix_mcp_oauth_authorizations_client_id'), table_name='mcp_oauth_authorizations')
    op.drop_table('mcp_oauth_authorizations')
    # ### end Alembic commands ###
