"""engineer messages

Revision ID: de9c03b6f9cf
Revises: a7b184d54fc9
Create Date: 2026-09-27 01:20:36.163214
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'de9c03b6f9cf'
down_revision: Union[str, None] = 'a7b184d54fc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engineer_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('game_session_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('lap', sa.Integer(), nullable=True),
    sa.Column('triggers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_sessions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engineer_messages_game_session_id'), 'engineer_messages', ['game_session_id'], unique=False)
    op.create_index(op.f('ix_engineer_messages_tenant_id'), 'engineer_messages', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_engineer_messages_tenant_id'), table_name='engineer_messages')
    op.drop_index(op.f('ix_engineer_messages_game_session_id'), table_name='engineer_messages')
    op.drop_table('engineer_messages')
    # ### end Alembic commands ###
